# Enable logging
logger:
  
esphome:
  name: eco_light-1
  platform: ESP32
  board: ttgo-lora32-v1
  on_boot:
    then:
      - logger.log: "ESPHome is starting"

wifi:
  ssid: "HTLLE-MTLAB"
  password: "wifi4life"

  #manual_ip:
   # static_ip: "192.168.5.100"
   # gateway: "192.168.5.254"
   # subnet: "255.255.255.0"
 

  
api: 
  password: "Oj9wOCw9J6Re86E7UcRE0+z9ySBIcwXk8QT2MKUolxo="
  
  

i2c:
  sda: 4
  scl: 15
  scan: True
  id: bus_a

font:
  - file: "gfonts://Ubuntu Mono"
    id: font_name
    size: 23
  - file: 
      type: gfonts
      family: "Ubuntu Mono"
      weight: bold
    id: font_name_bold
    size: 44
  



display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    id: oled_display
    reset_pin: 16
    lambda: |-
      it.print(0, 0, id(font_name), "Hello Welt!");
    
      



output:
  - platform: ledc
    pin: 12
    id: LED_blue
  
  - platform: ledc
    pin: 13
    id: LED_green

  - platform: ledc
    pin: 21
    id: LED_red

light:
  - platform: rgb
    name: "RGB LED"
    red: LED_red
    blue: LED_blue
    green: LED_green
