# ESP home configuration
esphome:
  name: ecolight
  platform: ESP32
  board: ttgo-lora32-v1

# definition of the i2c bus
i2c:
  sda: 4
  scl: 15
  scan: True
  id: bus_a

# font to be used
font:
  - file: "gfonts://Ubuntu Mono"
    id: font_name
    size: 38
  - file: 
      type: gfonts
      family: "Ubuntu Mono"
      weight: bold
    id: font_name_bold
    size: 12

#display to be used
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    id: oled_display
    reset_pin: 16
    lambda: |-
      it.print(0, 0, id(font_name), "Hello World!");

