# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support 
# documentation.

name: Aggregator

on:
  push:
    branches: [ "main" ]
    paths:
      - 'aggregator/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      working-directory: aggregator
      run: mvn -B package --file pom.xml

    - name: Pull H2 Docker image
      run: docker pull jesperdj/h2

    - name: Build and run H2 container
      run: docker run -d -p 8082:8082 -p 9092:9092 --name h2Database jesperdj/h2
