name: ttgo-lora-v1

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: ecolight_ttgo-lora-v1.yml
      name: Your Project Name
