# builds the hardware image for the ttgo-lora-v1 board
name: ttgo-lora-v1

on:
  push:
    branches: [ "main" ]
    paths:
      - 'hardware/**'
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    uses: esphome/build-action@v1.8.0
    with:
      files: hardware/ecolight_ttgo-lora-v1.yml
      name: ecolight
